<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlogSystem.muhanad.Abstractions\BlogSystem.muhanad.Abstractions.csproj" />
    <ProjectReference Include="..\BlogSystem.muhanad.Presistence\BlogSystem.muhanad.Presistence.csproj" />
  </ItemGroup>

</Project>
