<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlogSystem.muhanad.Presentation\BlogSystem.muhanad.Presentation.csproj" />
    <ProjectReference Include="..\BlogSystem.muhanad.Presistence\BlogSystem.muhanad.Presistence.csproj" />
    <ProjectReference Include="..\BlogSystem.muhanad.Service\BlogSystem.muhanad.Services.csproj" />
  </ItemGroup>

</Project>
